### ISSUE TITLE
CORS error 관련

### ISSUE THREAD

**Issue by mbmc7441** [pyeon-air/pyeon_air#20]
@highway92 형님 확인 부탁드립니다.

- 발생한 버그
CORS 에러

- 상황
로그인 시 해당 user 정보를 받아올 때 발생

- error 정보
Access to XMLHttpRequest at 'http://localhost:8000/management/member_api' from origin 'http://localhost:3000' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.
xhr.js:210          GET http://localhost:8000/management/member_api net::ERR_FAILED 200 

아직 CORS error 가 발생하네요 main branch 에서 pull 했는데 혹시 제가 빼먹은게 있을까요?

**Comment by highway92** [comment]
<img width="1171" alt="스크린샷 2022-02-20 오후 5 29 28" src="https://user-images.githubusercontent.com/75239649/154834777-0af92b37-c261-49a9-8af8-7e9a789faffb.png">
@mbmc7441  pyeonAir 안에 settings.py 가 있을거에요. 밑으로 내려보면 cors whitelist가 있을텐데 거기에 사진과 같이 url을 추가해주세요. 저도 테스트 해보고 main에 반영시켜 두겠습니다.

**Comment by mbmc7441** [comment]
@highway92 해결했습니다. 
감사합니니다!!
