### ISSUE TITLE
member 앱 Account 관련 버그

### ISSUE THREAD

**Issue by highway92** [pyeon-air/pyeon_air#21]
@Dongmin-Sim 
@donghyeon95 
JWT 토큰을 사용한 로그인 구현 중에 알아낸 사실입니다.

- django 에서는 user model을 만들때 장고에서 미리 만들어 둔 user객체를 상속받아 만들어야 한다고 합니다.
- 그 예시로는 로그인, 로그아웃, 인증, 인가와 관련된 많은 제약이 있을 것으로 예상됩니다.
- https://docs.djangoproject.com/en/4.0/ref/contrib/auth/
- 현재의 member 앱의 Account는 user의 기능을 수행할 수 없기때문에 대대적인 수정이 필요합니다.

**Comment by Dongmin-Sim** [comment]
찾아보았는데 User객체를 상속받거나 하는 방식으로 커스텀 User를 만들 수 있는 것 같습니다. 이미 보셨을 수도 있겠지만 아래 글 참고해보시는 것도 좋을 것 같습니다
- https://wayhome25.github.io/django/2017/05/18/django-auth/
- https://wikidocs.net/6651
- https://yonghyunlee.gitlab.io/python/user-extend/

**Comment by highway92** [comment]
로그인 기능을 구현하며 해당 부분 수정하여 [commit](https://github.com/pyeon-air/pyeon_air/commit/3f40acbde175b3161d063dc0c911536ec564e62e) 하였습니다.
