### ISSUE TITLE
bad request 400 관련하여

### ISSUE THREAD

**Issue by mbmc7441** [pyeon-air/pyeon_air#23]
안녕하세요.

저번 회의때 문제였던  bad request 400 관련해서 글씁니다.

해당 문제는 url로 post 요청시 아래 사진처럼 기존에는 username , password를 변수에 담아 하나로 요청보냈지만 이 부분에서 잘못된 구문으로 인식하여 생긴 오류인거 같습니다.  지금은 정상적으로 요청을 받은상태 이구요.
<img width="471" alt="스크린샷 2022-02-24 오후 3 51 19" src="https://user-images.githubusercontent.com/98802047/155474094-5a6e1d55-73b7-4dc9-ba60-d003985bed01.png">

<img width="1424" alt="스크린샷 2022-02-24 오후 3 50 30" src="https://user-images.githubusercontent.com/98802047/155473985-6873c0e3-6019-472b-b6fc-eca408395e98.png">

문제는 정확하게 아이디와 비밀번호를 입력해서 보내면 토큰을 보내주지만 다른아이디와 비밀번호를 입력하게되면 똑같이 400번 오류가 생기고
도커에는  {'username': 'None'} 로 나오긴 하더라구요. 확인부탁드립니다!

추가적으로 하나  요청사항이 있습니다.
post로 요청하고 로그인에 정상적으로 성공했을때나 실패했을때 loginSuccess , loginFail 같은 값도 같이 받으면 구문처리 할때 조금더 편할거 같습니다.

감사합니다!

**Comment by highway92** [comment]
1. 다른 아이디 비밀번호가 들어왔을 경우 status 401과 함께 {"message" : "fail"}이 response 되게 설정이 되어있습니다. 이 부분은 설정한대로 잘 동작하는 것으로 보이는데  어떤 부분을 확인 하고 싶은것인지 조금만 자세히 설명 부탁드립니다.

2.
성공했을 경우  {"user" : username, "token" : token }    http status 200
request body 에 문제가 있을 경우 http status 409
아이디나 비밀번호가 잘못되어 DB에서 유저를 인식할 수 없는 경우 http status 401
이 Response 됩니다. -> 구문처리는 http status 값으로 하는 것이 더욱 적절하다고 생각됩니다. 혹시나 구현상의 어려움이 있다면 말씀해주세요

**Comment by highway92** [comment]
도커에는 {'username': 'None'} 로 나오긴 하더라구요. 확인부탁드립니다!

이 부분은 Django 코드상에서 일어나는 것이라 다음 PR때 삭제 될 예정입니다. 정상적인 것이니 걱정안하셔도 됩니다. 👍

**Comment by mbmc7441** [comment]
제가 착각 했네요....ㅎㅎㅎ 정상적으로 동작하고 있습니다.

구문처리 같은경우 http status 로 처리 하도록 하겠습니다.

추가적으로 cookie에 토큰저장하는 것까지 해놓았습니다.

**Comment by highway92** [comment]
잘되니 다행입니다~ 사소한 거라도 의견 필요하면 언제든지 말해줘요 :)
