### ISSUE TITLE
BUG : Django container docker-compose up 버그입니다.

### ISSUE THREAD

**Issue by highway92** [pyeon-air/pyeon_air#37]
## 기본정보
- 제목은 '**BUG: 버그 한 줄 요약**'의 형식으로 작성
- **issue를 받는 사람 태그** 혹은 페이지 우측에 **Assignees 지정**

## 1. 발생 버그
docker-compose up 시 django container에서  qr code no module 에러가 발생합니다.
- 발생한 **버그를 한 줄 정도의 텍스트로 설명**해주세요.

## 2. 재현 순서
1. main branch $docker-compose up
- 보는 사람이 **똑같이 버그를 재현할 수 있을 정도로 순서**를 적어주세요.

## 3. 세부 내용
<img width="1093" alt="스크린샷 2022-03-23 오후 3 30 21" src="https://user-images.githubusercontent.com/75239649/159637679-cb14c9de-995d-4b24-a891-c91f8a723230.png">

- **버그에 대한 사진과 세부 내용**을 적어주시고 **해결을 위해 시도한 방법**이 있다면 작성해주세요.

## 4. 추가 내용

- **버그와 관련된 추가 정보** 혹은 **관련된 기능적인 요청**이 있을 경우에 간략하게 적어주세요. 없다면 비워주시면 됩니다.

**Comment by Dongmin-Sim** [comment]
requirement.txt 변경되서 생기는 오류 같아요 
docker-compose up --build 로 다시 실행하거나, 
위가 안되면 컨테이너, 이미지, 볼륨 날리고 다시 up 해주세요
해도 안되면 다시 멘션 주세요
<img width="830" alt="image" src="https://user-images.githubusercontent.com/74139156/159638863-7d06af22-9a3e-4c76-a7c6-42ec598087b4.png">

**Comment by highway92** [comment]
docker-compose build로 해결했습니다.
다만 migration 폴더들이 이미 있는 상태에서 docker-compose up을 하게되면 에러가 발생하니
build를 새로 했을경우에는 기존 migration 폴더를 다 지우고 docker-compose up을 해주세요.
(아래와 같은 에러가 발생했을때의 경우 입니다.)
<img width="924" alt="스크린샷 2022-03-23 오후 5 21 23" src="https://user-images.githubusercontent.com/75239649/159654660-90db2f9f-1432-4577-8d44-f1910ef87d92.png">
